name: Deploy_OpenVidu

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build_Docker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker run --detach=true -p 4443:4443 --rm -e OPENVIDU_SECRET=MY_SECRET openvidu/openvidu-dev:2.24.0
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Build with Maven
      run: mvn --batch-mode spring-boot:run &
      working-directory: ./openvidu-basic-java
    - name: Build the server
      run: |
        npm install --location=global http-server
        http-server openvidu-tutorials-tests/openvidu-hello-world/web &
      working-directory: .
    - name: TestHelloWord
      run: mvn test -Dtest="HelloWordTest"
      working-directory: ./Tests/OpenviduTests
